name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: gldf-sign

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macOS-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-freebsd
            os: ubuntu-latest
            sysroot: sysroots/freebsd

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Set up sysroot (FreeBSD)
      if: matrix.sysroot
      run: |
        echo "PKG_CONFIG_SYSROOT_DIR=${{ github.workspace }}/${{ matrix.sysroot }}" >> $GITHUB_ENV

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose

    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BINARY_NAME }}-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}
